/*
* File: enu2lla.c
*
*
*   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
*
*   This file is an S-function produced by the S-Function
*   Builder which only recognizes certain fields.  Changes made
*   outside these fields will be lost the next time the block is
*   used to load, edit, and resave this file. This file will be overwritten
*   by the S-function Builder block. If you want to edit this file by hand,
*   you must change it only in the area defined as:
*
*        %%%-SFUNWIZ_defines_Changes_BEGIN
*        #define NAME 'replacement text'
*        %%% SFUNWIZ_defines_Changes_END
*
*   DO NOT change NAME--Change the 'replacement text' only.
*
*   For better compatibility with the Simulink Coder, the
*   "wrapper" S-function technique is used.  This is discussed
*   in the Simulink Coder's Manual in the Chapter titled,
*   "Wrapper S-functions".
*
*  -------------------------------------------------------------------------
* | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
*  -------------------------------------------------------------------------
*
* Created: Fri Oct 18 11:51:58 2024
*/

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                enu2lla

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     6

/* Input Port  0 */
#define IN_PORT_0_NAME                 u0
#define INPUT_0_DIMS_ND                {1,1}
#define INPUT_0_NUM_ELEMS              1
#define INPUT_0_WIDTH                  1
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  real_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define INPUT_0_UNIT                   ""
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  0
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            9
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 u1
#define INPUT_1_DIMS_ND                {1,1}
#define INPUT_1_NUM_ELEMS              1
#define INPUT_1_WIDTH                  1
#define INPUT_DIMS_1_COL               1
#define INPUT_1_DTYPE                  real_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define INPUT_1_UNIT                   ""
#define IN_1_BUS_BASED                 0
#define IN_1_BUS_NAME
#define IN_1_DIMS                      1-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  0
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            9
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125

/* Input Port  2 */
#define IN_PORT_2_NAME                 u2
#define INPUT_2_DIMS_ND                {1,1}
#define INPUT_2_NUM_ELEMS              1
#define INPUT_2_WIDTH                  1
#define INPUT_DIMS_2_COL               1
#define INPUT_2_DTYPE                  real_T
#define INPUT_2_COMPLEX                COMPLEX_NO
#define INPUT_2_UNIT                   ""
#define IN_2_BUS_BASED                 0
#define IN_2_BUS_NAME
#define IN_2_DIMS                      1-D
#define INPUT_2_FEEDTHROUGH            1
#define IN_2_ISSIGNED                  0
#define IN_2_WORDLENGTH                8
#define IN_2_FIXPOINTSCALING           1
#define IN_2_FRACTIONLENGTH            9
#define IN_2_BIAS                      0
#define IN_2_SLOPE                     0.125

/* Input Port  3 */
#define IN_PORT_3_NAME                 u3
#define INPUT_3_DIMS_ND                {1,1}
#define INPUT_3_NUM_ELEMS              1
#define INPUT_3_WIDTH                  1
#define INPUT_DIMS_3_COL               1
#define INPUT_3_DTYPE                  real_T
#define INPUT_3_COMPLEX                COMPLEX_NO
#define INPUT_3_UNIT                   ""
#define IN_3_BUS_BASED                 0
#define IN_3_BUS_NAME
#define IN_3_DIMS                      1-D
#define INPUT_3_FEEDTHROUGH            1
#define IN_3_ISSIGNED                  0
#define IN_3_WORDLENGTH                8
#define IN_3_FIXPOINTSCALING           1
#define IN_3_FRACTIONLENGTH            9
#define IN_3_BIAS                      0
#define IN_3_SLOPE                     0.125

/* Input Port  4 */
#define IN_PORT_4_NAME                 u4
#define INPUT_4_DIMS_ND                {1,1}
#define INPUT_4_NUM_ELEMS              1
#define INPUT_4_WIDTH                  1
#define INPUT_DIMS_4_COL               1
#define INPUT_4_DTYPE                  real_T
#define INPUT_4_COMPLEX                COMPLEX_NO
#define INPUT_4_UNIT                   ""
#define IN_4_BUS_BASED                 0
#define IN_4_BUS_NAME
#define IN_4_DIMS                      1-D
#define INPUT_4_FEEDTHROUGH            1
#define IN_4_ISSIGNED                  0
#define IN_4_WORDLENGTH                8
#define IN_4_FIXPOINTSCALING           1
#define IN_4_FRACTIONLENGTH            9
#define IN_4_BIAS                      0
#define IN_4_SLOPE                     0.125

/* Input Port  5 */
#define IN_PORT_5_NAME                 u5
#define INPUT_5_DIMS_ND                {1,1}
#define INPUT_5_NUM_ELEMS              1
#define INPUT_5_WIDTH                  1
#define INPUT_DIMS_5_COL               1
#define INPUT_5_DTYPE                  real_T
#define INPUT_5_COMPLEX                COMPLEX_NO
#define INPUT_5_UNIT                   ""
#define IN_5_BUS_BASED                 0
#define IN_5_BUS_NAME
#define IN_5_DIMS                      1-D
#define INPUT_5_FEEDTHROUGH            1
#define IN_5_ISSIGNED                  0
#define IN_5_WORDLENGTH                8
#define IN_5_FIXPOINTSCALING           1
#define IN_5_FRACTIONLENGTH            9
#define IN_5_BIAS                      0
#define IN_5_SLOPE                     0.125
#define NUM_OUTPUTS                    3

/* Output Port  0 */
#define OUT_PORT_0_NAME                y0
#define OUTPUT_0_DIMS_ND               {1,1}
#define OUTPUT_0_NUM_ELEMS             1
#define OUTPUT_0_WIDTH                 1
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUTPUT_0_UNIT                  ""
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     1-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                y1
#define OUTPUT_1_DIMS_ND               {1,1}
#define OUTPUT_1_NUM_ELEMS             1
#define OUTPUT_1_WIDTH                 1
#define OUTPUT_DIMS_1_COL              1
#define OUTPUT_1_DTYPE                 real_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUTPUT_1_UNIT                  ""
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     1-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125

/* Output Port  2 */
#define OUT_PORT_2_NAME                y2
#define OUTPUT_2_DIMS_ND               {1,1}
#define OUTPUT_2_NUM_ELEMS             1
#define OUTPUT_2_WIDTH                 1
#define OUTPUT_DIMS_2_COL              1
#define OUTPUT_2_DTYPE                 real_T
#define OUTPUT_2_COMPLEX               COMPLEX_NO
#define OUTPUT_2_UNIT                  ""
#define OUT_2_BUS_BASED                0
#define OUT_2_BUS_NAME
#define OUT_2_DIMS                     1-D
#define OUT_2_ISSIGNED                 1
#define OUT_2_WORDLENGTH               8
#define OUT_2_FIXPOINTSCALING          1
#define OUT_2_FRACTIONLENGTH           3
#define OUT_2_BIAS                     0
#define OUT_2_SLOPE                    0.125
#define NPARAMS                        0
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           0
#define SOURCEFILES                    "__SFB__"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             0
#define CREATE_DEBUG_MEXFILE           0
#define SAVE_CODE_ONLY                 1
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#include <math.h>

extern void enu2lla_Outputs_wrapper(const real_T *u0,
                                    const real_T *u1,
                                    const real_T *u2,
                                    const real_T *u3,
                                    const real_T *u4,
                                    const real_T *u5,
                                    real_T *y0,
                                    real_T *y1,
                                    real_T *y2);

/*====================*
* S-function methods *
*====================*/
/* Function: mdlInitializeSizes ===============================================
* Abstract:
*   Setup sizes of the various vectors.
*/
static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NPARAMS);
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return;                            /* Parameter mismatch will be reported by Simulink */
    }

    ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);
    ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);
    if (!ssSetNumInputPorts(S, NUM_INPUTS))
        return;

    /* Input Port 0 */
    ssSetInputPortWidth(S, 0, INPUT_0_NUM_ELEMS);
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

    /* Input Port 1 */
    ssSetInputPortWidth(S, 1, INPUT_1_NUM_ELEMS);
    ssSetInputPortDataType(S, 1, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/

    /* Input Port 2 */
    ssSetInputPortWidth(S, 2, INPUT_2_NUM_ELEMS);
    ssSetInputPortDataType(S, 2, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 2, 1);/*direct input signal access*/

    /* Input Port 3 */
    ssSetInputPortWidth(S, 3, INPUT_3_NUM_ELEMS);
    ssSetInputPortDataType(S, 3, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 3, 1);/*direct input signal access*/

    /* Input Port 4 */
    ssSetInputPortWidth(S, 4, INPUT_4_NUM_ELEMS);
    ssSetInputPortDataType(S, 4, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 4, INPUT_4_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 4, 1);/*direct input signal access*/

    /* Input Port 5 */
    ssSetInputPortWidth(S, 5, INPUT_5_NUM_ELEMS);
    ssSetInputPortDataType(S, 5, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 5, INPUT_5_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 5, 1);/*direct input signal access*/

    /*
    * Configure the Units for Input Ports
    */
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

        #if defined(MATLAB_MEX_FILE)

        UnitId inUnitIdReg;
        ssRegisterUnitFromExpr(S, INPUT_0_UNIT, &inUnitIdReg);
        if (inUnitIdReg != INVALID_UNIT_ID) {
            ssSetInputPortUnit(S, 0, inUnitIdReg);
        } else {
            ssSetLocalErrorStatus(S,
                                  "Invalid Unit provided for input port u0 of S-Function enu2lla");
            return;
        }

        ssRegisterUnitFromExpr(S, INPUT_1_UNIT, &inUnitIdReg);
        if (inUnitIdReg != INVALID_UNIT_ID) {
            ssSetInputPortUnit(S, 1, inUnitIdReg);
        } else {
            ssSetLocalErrorStatus(S,
                                  "Invalid Unit provided for input port u1 of S-Function enu2lla");
            return;
        }

        ssRegisterUnitFromExpr(S, INPUT_2_UNIT, &inUnitIdReg);
        if (inUnitIdReg != INVALID_UNIT_ID) {
            ssSetInputPortUnit(S, 2, inUnitIdReg);
        } else {
            ssSetLocalErrorStatus(S,
                                  "Invalid Unit provided for input port u2 of S-Function enu2lla");
            return;
        }

        ssRegisterUnitFromExpr(S, INPUT_3_UNIT, &inUnitIdReg);
        if (inUnitIdReg != INVALID_UNIT_ID) {
            ssSetInputPortUnit(S, 3, inUnitIdReg);
        } else {
            ssSetLocalErrorStatus(S,
                                  "Invalid Unit provided for input port u3 of S-Function enu2lla");
            return;
        }

        ssRegisterUnitFromExpr(S, INPUT_4_UNIT, &inUnitIdReg);
        if (inUnitIdReg != INVALID_UNIT_ID) {
            ssSetInputPortUnit(S, 4, inUnitIdReg);
        } else {
            ssSetLocalErrorStatus(S,
                                  "Invalid Unit provided for input port u4 of S-Function enu2lla");
            return;
        }

        ssRegisterUnitFromExpr(S, INPUT_5_UNIT, &inUnitIdReg);
        if (inUnitIdReg != INVALID_UNIT_ID) {
            ssSetInputPortUnit(S, 5, inUnitIdReg);
        } else {
            ssSetLocalErrorStatus(S,
                                  "Invalid Unit provided for input port u5 of S-Function enu2lla");
            return;
        }

        #endif

    }

    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
        return;

    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_NUM_ELEMS);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_NUM_ELEMS);
    ssSetOutputPortDataType(S, 1, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

    /* Output Port 2 */
    ssSetOutputPortWidth(S, 2, OUTPUT_2_NUM_ELEMS);
    ssSetOutputPortDataType(S, 2, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);

    /*
    * Configure the Units for Output Ports
    */
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

        #if defined(MATLAB_MEX_FILE)

        UnitId outUnitIdReg;
        ssRegisterUnitFromExpr(S, OUTPUT_0_UNIT, &outUnitIdReg);
        if (outUnitIdReg != INVALID_UNIT_ID) {
            ssSetOutputPortUnit(S, 0, outUnitIdReg);
        } else {
            ssSetLocalErrorStatus(S,
                                  "Invalid Unit provided for output port y0 of S-Function enu2lla");
            return;
        }

        ssRegisterUnitFromExpr(S, OUTPUT_1_UNIT, &outUnitIdReg);
        if (outUnitIdReg != INVALID_UNIT_ID) {
            ssSetOutputPortUnit(S, 1, outUnitIdReg);
        } else {
            ssSetLocalErrorStatus(S,
                                  "Invalid Unit provided for output port y1 of S-Function enu2lla");
            return;
        }

        ssRegisterUnitFromExpr(S, OUTPUT_2_UNIT, &outUnitIdReg);
        if (outUnitIdReg != INVALID_UNIT_ID) {
            ssSetOutputPortUnit(S, 2, outUnitIdReg);
        } else {
            ssSetLocalErrorStatus(S,
                                  "Invalid Unit provided for output port y2 of S-Function enu2lla");
            return;
        }

        #endif

    }

    ssSetNumPWork(S, 0);
    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);
    ssSetSimulinkVersionGeneratedIn(S, "24.1");

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetRuntimeThreadSafetyCompliance(S, RUNTIME_THREAD_SAFETY_COMPLIANCE_FALSE);
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
                                         int_T port,
                                         const DimsInfo_T *dimsInfo)
{
    if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
        return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
                                          int_T port,
                                          const DimsInfo_T *dimsInfo)
{
    if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
        return;
}

#endif

/* Function: mdlInitializeSampleTimes =========================================
* Abstract:
*    Specifiy  the sample time.
*/
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetModelReferenceSampleTimeDefaultInheritance(S);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
* Abstract:
*    This function is called once at start of model execution. If you
*    have states that should be initialized once, this is the place
*    to do it.
*/
static void mdlStart(SimStruct *S)
{
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
*
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const real_T *u0 = (real_T *) ssGetInputPortRealSignal(S, 0);
    const real_T *u1 = (real_T *) ssGetInputPortRealSignal(S, 1);
    const real_T *u2 = (real_T *) ssGetInputPortRealSignal(S, 2);
    const real_T *u3 = (real_T *) ssGetInputPortRealSignal(S, 3);
    const real_T *u4 = (real_T *) ssGetInputPortRealSignal(S, 4);
    const real_T *u5 = (real_T *) ssGetInputPortRealSignal(S, 5);
    real_T *y0 = (real_T *) ssGetOutputPortRealSignal(S, 0);
    real_T *y1 = (real_T *) ssGetOutputPortRealSignal(S, 1);
    real_T *y2 = (real_T *) ssGetOutputPortRealSignal(S, 2);
    real_T latRef, longRef, heightRef, EVal, NVal, UVal;
    /* Define some intermediate variables */
    real_T N_phi, X, Y, Z, N_phi_ref, Xref, Yref, Zref; // for ECEF coordinates
    real_T esq, p, F, G, c, s, kappa, P, Q, ro, U, V, zo, h, phi, lambda; // for ECEF to LLA coordinates
    /* Define major and minor radii of the Earth from WGS84 ellipsoid model */
    const real_T a = 6378137.0;
    const real_T b = 6356752.314245;
    /* Bring in position inputs and assign to short named variables */
    latRef = u0[0]*M_PI/180;
    longRef = u1[0]*M_PI/180;
    heightRef = u2[0];
    EVal = u3[0];
    NVal = u4[0];
    UVal = u5[0];

    N_phi_ref = a*a/sqrt(a*a*cos(latRef)*cos(latRef) + b*b*sin(latRef)*sin(latRef));
    Xref = (N_phi_ref + heightRef)*cos(latRef)*cos(longRef);
    Yref = (N_phi_ref + heightRef)*cos(latRef)*sin(longRef);
    Zref = ((b*b/a/a)*N_phi_ref + heightRef)*sin(latRef);

    X = Xref - sin(longRef)*EVal - sin(latRef)*cos(longRef)*NVal + cos(latRef)*cos(longRef)*UVal;
    Y = Yref + cos(longRef)*EVal - sin(latRef)*sin(longRef)*NVal + cos(latRef)*sin(longRef)*UVal;
    Z = Zref + cos(latRef)*NVal + sin(latRef)*UVal;

    esq = (a*a - b*b)/(a*a);
    p = sqrt(X*X + Y*Y);
    F = 54.0*b*b*Z*Z;
    G = p*p + (1 - esq)*Z*Z - esq*(a*a - b*b);
    c = esq*esq*F*p*p/G/G/G;
    s = cbrt(1 + c + sqrt(c*c + 2*c));
    kappa = s + 1 + 1/s;
    P = F/(3*kappa*kappa*G*G);
    Q = sqrt(1 + 2*P*esq*esq);
    ro = -P*esq*p/(1+Q) + sqrt(a*a/2*(1+(1/Q)) - P*(1-esq)*Z*Z/Q/(1+Q) - P*p*p/2);
    U = sqrt((p-(esq*ro))*(p-(esq*ro)) + Z*Z);
    V = sqrt((p-(esq*ro))*(p-(esq*ro)) + (1 - esq)*Z*Z);
    zo = b*b*Z/a/V;
    h = U*(1 - (b*b)/(a*V)); // altitude
    phi = atan((Z+zo*(a*a - b*b)/b/b)/p); // latitude
    lambda = atan2(Y,X); // longitude

    y0[0] = phi*180/M_PI;
    y1[0] = lambda*180/M_PI;
    y2[0] = h;}

/* Function: mdlTerminate =====================================================
* Abstract:
*    In this function, you should perform any actions that are necessary
*    at the termination of a simulation.  For example, if memory was
*    allocated in mdlStart, this is the place to free it.
*/
static void mdlTerminate(SimStruct *S)
{
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
